### ISSUE TITLE
Multiline statictext names

### ISSUE THREAD

**Issue by joonaspaakko** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#100]
### Discussed in https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **softhorizons** August 25, 2022</sup>
The editor automatically splits multiline statictext into multiple statictext's inside a group, something like:
```
var staticTextOneTwo = grpMain.add("group"); 
    staticTextOneTwo.add("statictext", undefined, "One line", {name: "staticTextOneTwo"}); 
    staticTextOneTwo.add("statictext", undefined, "followed by another", {name: "staticTextOneTwo"}); 
```

However
- the group isn't named
- the individual statictext's have the same name

This makes it very inconvenient to access the auto-generated group and sub-elements. You really want to access the group as control.grpMain.staticTextOneTwo. I find myself manually creating a group of single-line statictext's to work around this.

It would be great if the editor emitted:
```
var staticTextOneTwo = grpMain.add("group", undefined, {name: "staticTextOneTwo"}); 
    staticTextOneTwo.add("statictext", undefined, "One line", {name: "statictext1"}); 
    staticTextOneTwo.add("statictext", undefined, "followed by another", {name: "statictext2"}); 
```
Though really, it might be cleaner to not emit names at all for the single-line statictexts since it makes more sense to access them as ...staticTextOneTwo.children[0, 1, ...]. How about it?</div>

**Comment by joonaspaakko** [comment]
Now the multiline `staticText` items parent `group` gets the item name and the actual child text items are unnamed. 

> Thought I'm not sure if it would get a lot of use, I also added a helper function for fetching the text `itemName.getText()`.

![CleanShot 2022-09-12 at 00 44 11@2x](https://user-images.githubusercontent.com/1164476/189550309-2b27150c-4868-4899-a79f-8a1eedb932e1.png)

**Comment by softhorizons** [comment]
Beautiful! Thank you.
