### ISSUE TITLE
Support for EnablingGroup component

### ISSUE THREAD

**Issue by daun** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#107]
Hi! Really appreciate the work you're doing on the dialog builder, it's a wonderful tool. Thanks a lot.

One question I had when trying to build out a custom panel is about the [EnablingGroup](https://www.indesignjs.de/extendscriptAPI/indesign-latest/#EnablingGroup.html) element that allows enabling/disabling the whole group by un/checking a checkbox next to its title. I've seen it in some example panels, but can't get it to work. Do you know if this is supported at all?

<img width="288" alt="Radiobuttons" src="https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/assets/22225348/2b01abf7-dace-4a3d-bac3-3e683dbfc107">

I've found an example online, but it uses a different (compatible?) way of adding elements to dialogs than SDB does:

```js
var dialog = app.dialogs.add({name:"Dialog"}); 
var group = dialog.enablingGroups.add({staticLabel:"Optional", checkedState:true}); 
group.staticTexts.add({staticLabel:"Lorem ipsum"}); 
```

Trying this in the output of SDB throws errors that `UI element type enablinggroup is unknown or invalid`.

```js
var dialog = new Window("palette");
var group = dialog.add("enablinggroup", undefined, undefined});
```

I'm new to this, so maybe I'm missing an important distinction between these two ways of creating dialogs...

**Comment by joonaspaakko** [comment]
First time I've ever seen that. Any kind of mentions of it are very slim. It seems to be a Indesign specific thing that is different from SUI... From what I could find, people refer to it as like Indesign built-in dialog system or something. Best guess I have after like 10 minutes of fruitless googling is that it's like Indesign's own flavor of SUI maybe used in some internal dialogs? Although, they do use similar collapsible panels in the settings of other applications... It is quite an old thing from the looks of it, but I guess I was never that deeply into Indesign scripting and never bumped into it. As far as I know, there is nothing quite like that in SUI and the code isn't compatible or even close enough that it would make sense to replicate at this point.

> There was a similar question here #97 about what is basically the same idea with a chevron instead of a checkbox.  Without refreshing my memory by reading any of that post, I'm going to guess the biggest issue I had was that I was trying to be a little too ambitious trying to replicate that exactly functionality and I couldn't attach a click event to the panel title, so it didn't really go anywhere.

With my knowledge... Which isn't infinite, the best you can do is probably something like this:

![CleanShot 2023-10-26 at 22 51 19](https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/assets/1164476/59c68b24-db00-4445-b349-4bd554dae48a)

> Panel without a title + Checkbox outside functioning as the clickable title

```js
/*
Code for Import https://scriptui.joonas.me — (Triple click to select): 
{"activeId":6,"items":{"item-0":{"id":0,"type":"Dialog","parentId":false,"style":{"enabled":true,"varName":null,"windowType":"Dialog","creationProps":{"su1PanelCoordinates":false,"maximizeButton":false,"minimizeButton":false,"independent":false,"closeButton":true,"borderless":false,"resizeable":false},"text":"Dialog","preferredSize":[0,0],"margins":16,"orientation":"column","spacing":10,"alignChildren":["center","top"]}},"item-1":{"id":1,"type":"Button","parentId":3,"style":{"enabled":true,"varName":null,"text":"Button","justify":"center","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-3":{"id":3,"type":"Panel","parentId":5,"style":{"enabled":true,"varName":null,"creationProps":{"borderStyle":"etched","su1PanelCoordinates":false},"text":"","preferredSize":[0,0],"margins":10,"orientation":"row","spacing":10,"alignChildren":["left","top"],"alignment":null}},"item-5":{"id":5,"type":"Group","parentId":0,"style":{"enabled":true,"varName":null,"preferredSize":[0,0],"margins":0,"orientation":"column","spacing":0,"alignChildren":["left","center"],"alignment":null}},"item-6":{"id":6,"type":"Checkbox","parentId":5,"style":{"enabled":true,"varName":null,"text":"Options","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-7":{"id":7,"type":"StaticText","parentId":3,"style":{"enabled":true,"varName":null,"creationProps":{"truncate":"none","multiline":false,"scrolling":false},"softWrap":false,"text":"StaticText","justify":"left","preferredSize":[0,0],"alignment":null,"helpTip":null}}},"order":[0,5,6,3,1,7],"settings":{"importJSON":true,"indentSize":false,"cepExport":false,"includeCSSJS":true,"showDialog":true,"functionWrapper":false,"afterEffectsDockable":false,"itemReferenceList":"None"}}
*/ 

// DIALOG
// ======
var dialog = new Window("dialog"); 
    dialog.text = "Dialog"; 
    dialog.orientation = "column"; 
    dialog.alignChildren = ["center","top"]; 
    dialog.spacing = 10; 
    dialog.margins = 16; 

// GROUP1
// ======
var group1 = dialog.add("group", undefined, {name: "group1"}); 
    group1.orientation = "column"; 
    group1.alignChildren = ["left","center"]; 
    group1.spacing = 0; 
    group1.margins = 0; 

var checkbox1 = group1.add("checkbox", undefined, undefined, {name: "checkbox1"}); 
    checkbox1.text = "Options"; 

// PANEL1
// ======
var panel1 = group1.add("panel", undefined, undefined, {name: "panel1"}); 
    panel1.orientation = "row"; 
    panel1.alignChildren = ["left","top"]; 
    panel1.spacing = 10; 
    panel1.margins = 10; 

var button1 = panel1.add("button", undefined, undefined, {name: "button1"}); 
    button1.text = "Button"; 

var statictext1 = panel1.add("statictext", undefined, undefined, {name: "statictext1"}); 
    statictext1.text = "StaticText"; 

// - - - - - - - - - - - - - - -
//   CUSTOMIZATIONS:
// - - - - - - - - - - - - - - -

checkbox1.value = true;
checkbox1.onClick = function( e ) {

    var checked = this.value;
    if ( !checked ) this.maxHeight = panel1.maximumSize.height;
    
    panel1.maximumSize.height = checked ? this.maxHeight : 0;
    dialog.layout.layout(true);
    
};

dialog.show();
```

**Comment by joonaspaakko** [comment]
If you are making a layout that is basically the same as in your screenshot, it might be better if you:

1. Change `Add border`into a panel with no title
2. Change `Corner type` into a checkbox
3. Wrap the 2 radiobuttons in a group ...and toggle that group just like in my example when `Corner type` is clicked.

> Though my original code example might be simpler.

**Comment by daun** [comment]
Thanks for the pointers! I'll try those out soon and report back. I think visually the solution where the checkbox is outside the group is perfectly fine. I've just never managed to get the autoscaling to behave as I wanted.

**Comment by joonaspaakko** [comment]
It occurred to me that not being able to run your example code and remembering the other issue kinda made me forget that the checkbox action wasn't to hide, but to disable, so while I think it's pretty self explanatory that you should then toggle `enabled` property... I still prepared this example just to show off the `parent` and `children` properties, which is what you might need if you wanted like an all purpose function that links a checkbox to its sibling item, which would be nice to have, if you have more than one of them.

![CleanShot 2023-10-29 at 18 11 51](https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/assets/1164476/98b9c6b7-f605-433d-9c6d-95cb53265656)

```js
checkbox1.value = true;
checkbox1.onClick = function( e ) {

    // parent = group1
    // children[0] = checkbox1
    // children[1] = panel1
    this.parent.children[1].enabled = checkbox1.value;
    
};
```
Or with a function that you can use on multiple `group > checkbox + panel` item combos:

```js
var linkCheckboxToSibling = function( params ) {
    
    var checkbox = params.target.children[0];
    var sibling  = params.target.children[1];
    
    // Defaults
    checkbox.value  = params.initValue;
    sibling.enabled = params.initValue;
    
    checkbox.onClick = function( e ) {
        
        sibling.enabled = checkbox.value;
        
    };
    
};

linkCheckboxToSibling({ initValue: false, target: group1 });
```

**Comment by daun** [comment]
Thanks for taking the time to create all these examples, really appreciate it. I especially like the last example of generalising the problem to work with the first and second child to serve as toggle and content area. I've now used it successfully in my current project — it's working like a charm :)
