### ISSUE TITLE
Request: Export to resource strings...

### ISSUE THREAD

**Issue by jedSavage** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#23]
An option to export to resource string format would be nice. [Script-UI-Resource-Strings](https://github.com/fabianmoronzirfas/extendscript/wiki/Script-UI-Resource-Strings).

**Comment by joonaspaakko** [comment]
I used to like formatting dialogs this way cause it's more compact, I guess, but I'm not a big fan of it anymore. 

I don't really have a strong reason not to add support for it, so I think I'll put it under consideration for now, but It's not going to be incredibly high in the priority.

Any particular reason why you prefer it, @jedSavage?

**Comment by jedSavage** [comment]
Mostly for the same reason, it's more compact and it's what I use when manually creating dialogs. Not a huge issue though, I'm just happy you created this in the first place. :)

**Comment by joonaspaakko** [comment]
Right. Currently, the `js` that handles the export is kind of a mess, so I would imagine doing this would require a lot of work. 

I've been kinda stuck working on issue #18  for quite a while. I wouldn't hold my breath waiting for this. That said, I might at least take a look at it when I start working on custom variable names (#24).

**Comment by joonaspaakko** [comment]
I decided there's just no reason to support resource strings as such. The closest you are going to get is this one: #54
