### ISSUE TITLE
Panel dropdowns forcefully closing (sometimes)

### ISSUE THREAD

**Issue by jedSavage** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#25]
I've noticed that sometimes the dropdowns do not stay open after clicking on them.  It seems to happen randomly but often.  I've [linked to a screencast](http://s000.tinyupload.com/download.php?file_id=14809331892888527444&t=1480933189288852744483163) of it happening.

[Here's a gif](https://user-images.githubusercontent.com/1164476/51933663-8029b280-240a-11e9-8426-a5b4e69cbd54.gif) with most of the original video (first 30seconds). 
And here's just the part with the issue: 
![alignchildrendropdownissue2](https://user-images.githubusercontent.com/1164476/51934075-72c0f800-240b-11e9-857b-d3ff0042fc1b.gif)

**Comment by joonaspaakko** [comment]
Thanks. I'll have to take a look at that. 

**This is more for me to look at when I start working on this:**

It almost looked like maybe the click event was triggered twice, toggling it on and off... but I have another theory... The plugin that I used to do those dropdowns (in a moment of laziness) closes the dropdown on mouseout. So it could be be that for some reason a `mouseout event` is triggered after the first `click event`, and that closes it... I wasn't able to trigger this behavior yet.

**Comment by joonaspaakko** [comment]
@jedSavage, I haven't been able to replicate this behavior. Could you try it in incognito mode? 

Since I feel like I've tried my all and I just can't make it happen, I'm thinking an extension could interfere with it. Seems unlikely, but it's easy enough to confirm. Could you also check the dev console to see if it spews any errors when this happens?

**Comment by jedSavage** [comment]
You may be right, I can't repeat it now either, so it's likely something to do with my setup here.

**Comment by joonaspaakko** [comment]
Alright. I'll keep it open for now and keep an eye on it.

**Comment by joonaspaakko** [comment]
I think it's time to close this one. I have tried to dig through commits from around that time you posted this, but it's not showing up.
