### ISSUE TITLE
Feature Request: Empty event callbacks on export....

### ISSUE THREAD

**Issue by jedSavage** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#32]
Would be nice to have a section of checkboxes (perhaps expandable) for each control where we can check various events (onClick, onEdit, etc...) and have empty callback functions generated on export.

![screen shot 03-08-19 at 09 47 am](https://user-images.githubusercontent.com/14342067/54042491-80466c00-4187-11e9-9749-5221f57c8c40.PNG)

**Comment by joonaspaakko** [comment]
I've given this a good amount of thought and I'm going to say no to this. 

I think It's too much work for what it is. Another thing is, if you make changes to the dialog and export it, you'd keep exporting empty event functions that you'd have to remove after each export if you've already written them.
