### ISSUE TITLE
Disable drag drop for Image and IconButton in the Preview

### ISSUE THREAD

**Issue by olegbutrin** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#44]
![image](https://user-images.githubusercontent.com/11036487/57578517-3dbb4b80-74b8-11e9-9e83-154c08f29c01.png)

After adding the Image or IconButton, it can be dragged (and duplicated) into any other text-based element. After dropping Image is removed from the structure and saved as part of the text in the text element.

![image](https://user-images.githubusercontent.com/11036487/57578556-ee294f80-74b8-11e9-8d3d-df1eb8fcd3f5.png)

**Comment by joonaspaakko** [comment]
@olegbutrin, thanks for the report. I fixed it by preventing image dragging. 

> This is related to a previous issue with the dialog preview `contenteditable` elements, that I lazily "fixed" by preventing pasting into those elements. It's not a great fix since it's just replacing a potentially huge problem with a slight hindrance. This image thing was something I forgot about.
