### ISSUE TITLE
CEP export (HTML)

### ISSUE THREAD

**Issue by joonaspaakko** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#46]
This is for everyone who always wanted to build websites using the ScriptUI layout... Or perhaps CEP panels. No judging from me either way.

- - - - 

A checklist for me for later use… **On CEP export:**

1. Grab HTML from the DOM
	* Remove dialog title? Hide it? Morph it into the <title>?
	* Add a CEP specific class that sort of stretches the dialog to cover the whole container with the help of some extra CSS (maybe?)
2. Grab dialog-preview.css (that has been compiled beforehand)
3. Grab CEP specific JS (jquery? or vanilla?) (I would imagine this to be like 30 lines tops. Just scaffolding for the most part. TabbedPanel and Dropdownlist would likely be the beefiest functions)
4. Link to font-awesome, jquery(?) and the fonts via a CDN.
	* With a little work, I could get rid of the need for font-awesome since it’s only used for a few items in the dialog preview.
5. Put it all together so it can be exported to clipboard or downloaded as a single .html file.

**Comment by derrickb** [comment]
Regarding the dialog title, I think it can be ignored entirely. We don't use the <title> in extensions anyway.

**Comment by Zhouxigui007** [comment]
it will be very very great that if your project can export HTML.
Because there are more and more developers use this CEP ways to develop their app.

**Comment by joonaspaakko** [comment]
@Zhouxigui007, won't be long before I start working on it. 1 more issue in the queue before I start working on the CEP export.

**Comment by joonaspaakko** [comment]
There's now a new button in the export window where you can find the CEP export and other options.

I also made a small sample panel: https://github.com/joonaspaakko/SDB-to-CEP-samples

![2019-06-21 01 01 34](https://user-images.githubusercontent.com/1164476/59884244-72c49300-93c0-11e9-87c1-6db32638c705.gif)
