### ISSUE TITLE
Request: capture show() result in variable

### ISSUE THREAD

**Issue by derrickb** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#47]
Currently dialogs are displayed without their return value captured, eg:
```javascript
dialog.show();
```
It would be really helpful for extending the code if the result is automatically captured in a variable, eg:
```javascript
var result = dialog.show();
```
This means elsewhere (eg. from a button click) we could call `dialog.close(100)` and `result` would now be `100`

If the result is not needed, then this variable is unused and does nothing. But if the developer needs to perform actions based on the return result of the dialog, then they'd currently have to edit the exported code from SDB.

Alternatively, do not add the `show()` call at all, and let us add it and assign to variable as needed. This would result in more reusable export code.

**Comment by joonaspaakko** [comment]
Seems weird to me that the alternative you suggest is to remove dialog.show(). I'm not sure how that's an alternative. 

The reason why that is there is so you can quickly export and run the code as is. 

Adding var result on your own doesn't seem like a huge burden for the user in my opinion.

**Comment by derrickb** [comment]
That's fair, and it isn't a lot of extra work for us to edit that line manually.

**Comment by joonaspaakko** [comment]
I'll close this since I believe your other request #48 makes this one kind of unnecessary and I've added it to the queue.
