### ISSUE TITLE
Request: wrap dialog in its own namespace

### ISSUE THREAD

**Issue by derrickb** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#48]
In order to make the exported dialogs more modular and to avoid name collisions, add an export option (or by default?) to wrap the exported code in its own function, and assigned to a (user-defined) variable name.

This is essentially a classic JavaScript module pattern and should fit into any developer's framework without needing to conform to specific bundlers, builders, etc.

In order to make this truly useful, the following features should be in place:
1. The dialog's Window object is returned as the final result, without its `show` method called
2. All of the dialog's components... groups, panels, buttons, etc... need to be accessible from the namespace, eg. `namespace.panel1.group1.button1` so events and callbacks can be added.

Proposed export:
```javascript
var namespace = (function () {

  var dialog = new Window("dialog"); 
    dialog.text = "Dialog"; 
    dialog.orientation = "column"; 
    dialog.alignChildren = ["center","top"]; 
    dialog.spacing = 10; 
    dialog.margins = 16; 

  var button1 = dialog.add("button"); 
    button1.text = "Button"; 
    button1.justify = "center";

    dialog.button1 = button1; //add some way to access via top-level namespace
      
  return dialog;

}());
```
This exported snippet can now be used from within the same script _or_ an external script, depending on the developer's needs and how they structure their code:
```javascript
namespace.button1.onClick = function () {
  alert('clicked!');
  namespace.close(100);
};

var result = namespace.show();
```

**Comment by joonaspaakko** [comment]
I personally kept there thoughts buried deep down because I felt it's a slippery slope. 

I think this could be added if I also added export options so you could choose to wrap it in a function but it isn't forced. I'd hate to force some people to demo remove whole bunch of lines on every export.

A slight concern is accessing each item. This was a concern from the start actually. Right now if you want to deep dive into these items using the dialog object, you need to anonymously traverse the messy structure. Would SDB just generate these at the bottom or right after the item var is created...?

**Comment by derrickb** [comment]
Yeah I think it would work great as an export option.

Regarding the item access, I think either generating at the bottom or the hybrid approach you propose in your comment on #31 would work great.

It should be stated that while yes, the generated code becomes "messier" when you add these type of accessors (dialog.group1.button1.etc...), I'd argue that for the developers who would benefit from this export option, the pros outweigh the cons and it's a fine trade-off.

SDB is, in my eyes, going to become an essential tool for ScriptUI development. With function wrapping like this applied, it can now be leveraged in large complicated CEP extensions with many dialogs and that may use a module bundling/building pipeline.

**Comment by joonaspaakko** [comment]
I agree. This should be a fairly painless addition. I have been thinking that maybe the CEP export (#46)  could be an option rather than its own export button... so at least it wouldn't be so lonely with other options... It might be a while before I add it though.

**Comment by joonaspaakko** [comment]
It's now in the export settings: 

![ScriptUI_Dialog_Builder_function_wrapper](https://user-images.githubusercontent.com/1164476/63655148-236a5c80-c78d-11e9-9e1a-6d2fa20fb40e.png)
