### ISSUE TITLE
Request: implement vertical TabbedPanel component

### ISSUE THREAD

**Issue by derrickb** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#49]
This may be a bit controversial because in itself it is not a native ScriptUI component, rather it is a combination of them.

See page 64 of "ScriptUI for Dummies" for screenshots and implementation details:
https://adobeindd.com/view/publications/a0207571-ff5b-4bbf-a540-07079bd21d75/y2c4/publication-web-resources/pdf/scriptui-2-13-f-2017.pdf

Essentially, it recreates the various "Preferences" dialogs found in the Adobe apps, where you select the "tab" from the `ListBox` and it changes the displayed panel/group.

Since you already have the base components implemented (ListBox, Group, Panel) perhaps it would be possible to construct something combining these? A customized ListBox where in addition to the "List Items" array, you specify a group or panel that each list item activates. The generated JSX should then have the minimal function logic required to do the tab switching.

(note: the dialog's height will be the maximum of the possible panels/groups that can be shown and I think that's okay)

![image](https://user-images.githubusercontent.com/1793769/58326072-a7761680-7e23-11e9-8e26-223ed159532a.png)

**Comment by joonaspaakko** [comment]
This has been in my personal todo list. I've never used this myself, so I have to play with it and see how it works before I decide if I want to add it.

For one... I thought tabbedpanel would've been easy to add, but it wasn't... So I don't want to commit to it before I know it's not going to make me lose my sanity.

**Comment by joonaspaakko** [comment]
Now it's finally added. 

![2020-02-16 22 13 44](https://user-images.githubusercontent.com/1164476/74612006-c9c66780-5109-11ea-842a-b34d0a7f5846.gif)
