### ISSUE TITLE
Request: Add the Options "justify", "multiline" and "readonly" the EditText editor

### ISSUE THREAD

**Issue by jetrotal** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#51]
These are some problematics properties, but they are useful too.

Justify can only work through some workarounds, here's one of them:

```
function test2(){  
    var w = new Window('dialog', 'Test');  
     
    var eResource = "EditText { properties:{multiline:false, readonly:true}, text:'<your message here>', justify:'center' } ";  
  
  
    var e = w.add(eResource);  
    e.characters = 20;  
    w.show();  
};  
test2(); 
```

this and others workarounds came from this discussion:
https://forums.adobe.com/thread/2085789

**Comment by joonaspaakko** [comment]
I'm feeling a bit hesitant, but I'll put this into consideration for now.

**Comment by jetrotal** [comment]
If you need examples of uses to it,
i'm currently working on a panel that depends highly on these options.

Here's the mockup i made to study the layout.
![image](https://user-images.githubusercontent.com/45118493/58872464-748d1780-869a-11e9-8278-e779184c4974.png)

And here's the panel as it leaves the Builder.
![image](https://user-images.githubusercontent.com/45118493/58872579-b8801c80-869a-11e9-8e89-9c8ba9097957.png)

I can edit it all after finishing the basic layout of my panel, but since i repeat these EditTexts in so many places, dragging and dropping clones of them could be a life saver.

**Comment by joonaspaakko** [comment]
I'm just at a point where I'm pretty swamped and trying to really consider the usefulness of a feature and how hard it is to implement. I'll likely add this, but I don't want to commit to it right now. I have... Not _that much_ in the queue, but the CEP export is eating a lot of time right now so I don't know how soon  I can release other features.

About the multiline... The default state is false, and there is technically a multiline option, it's just not visible in a sense. I realize now that if you want EditText to have the potential to have multiline text, but start from a single line, then the way it's implemented right now might not be enough...

There's the softWrap option, which makes text flow into multiple lines if its not wide enough to hold the text in one line. Also if you press enter to insert a forced line break, the export will also come out multiline. **Do you think a separate multiline checkbox is needed?**

**Comment by joonaspaakko** [comment]
Creation properties have now been added to the very bottom of the properties panel. I also added a fix for `EditText`'s `justify` property. 

![Screenshot_8_25_19__11_11_PM_creationprops](https://user-images.githubusercontent.com/1164476/63655190-dc309b80-c78d-11e9-8f02-a0337a02ee4c.png)
