### ISSUE TITLE
Request: Simple Syntax Editor

### ISSUE THREAD

**Issue by jetrotal** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#52]
Let's say the user wants to customize his items properties with some syntaxes that aren't supported by the Builder.

He has to rewrite the same code over and over again everytime he tweaks something in the builder.

What if we had some kind of syntax editor that stores unsuportted codes?

All the supported code would be locked out, 
and the custom ones wouldn't affect the editor at all. 

![image](https://user-images.githubusercontent.com/45118493/59177723-50668600-8b33-11e9-94e3-56338a823b96.png)

**Comment by jetrotal** [comment]
Now, thinking about it...
You could even expand this concept and make an Item dedicated to Custom Scripting:

![image](https://user-images.githubusercontent.com/45118493/59166934-ec2ccd80-8b04-11e9-873c-cb47afcba013.png)

I don't know if these suggestions would be against the main focus of the Builder, or if would it be confusing for the user, since it won't affect the Builder's preview.  
I see them as a killer feature for the Builder...

**Comment by joonaspaakko** [comment]
My argument against both, actually, is that these are things you can define sort of outside of the dialog created by SDB. 

The benefit in what you suggest is that you could slap these "custom" properties right next to where the item is created. That's the only one that came to mind anyways.

**So far I have been doing this:**

1. Make dialog in SDB
2. Write customization below the dialog before the dialog is shown. 
    - This kinda depends on how I wrap the dialog...
3. Make changes in SDB
4. Paste changes on top of my current dialog, above the customization.
5. Remove the `dialog.show();`

**So really the way I see it, the only hindrance right now is that you have to remove the `dialog.show();`.** There is no issue in terms of overwriting custom code as long as you place it outside the dialog.

> Recently I've been making `export settings`... (Not released yet)... and I haven't planned it yet, but I could add it as an option: `Place show() at the end` (or whatever) - So you could choose to not include it.

![](https://user-images.githubusercontent.com/1164476/59178972-45c6e380-8b69-11e9-8fca-f3bd7c68d2d7.gif)

And to be clear, all of these things where you would write custom code inside SDB seem a little counterproductive to me personally. **I don't want to discourage anyone from making these suggestions, I'll try to keep an open mind**, but  I can just picture myself writing code in the browser, then exporting it, pasting it to ESTK to debug it, then jump back to the browser, make changes, export, paste back to ESTK for debugging and repeat this like a hundred times. Not to mention, the editor in SDB, even if I added syntax highlighting, it can't be as good as whatever else I would be using. So I would likely need quite a bit of convincing to implement anything like this. **Anything that can't be circumvented effortlessly is definitely something I'm interested in implementing though.** Like for example the window type suggestion of yours in this issue  #50.

**Here's the example code:**

```Javascript
/* 
Code for Import https://scriptui.joonas.me — (Triple click to select): 
{"activeId":0,"items":{"item-0":{"id":0,"type":"Dialog","parentId":false,"style":{"varName":"dlg","text":"Dialog","preferredSize":[0,0],"margins":16,"orientation":"column","spacing":10,"alignChildren":["center","top"]}},"item-1":{"id":1,"type":"StaticText","parentId":0,"style":{"varName":"text","softWrap":false,"text":"StaticText","justify":"left","preferredSize":[0,0],"alignment":null,"helpTip":null}}},"order":[0,1]}
*/ 

// DLG
// ===
var dlg = new Window("dialog"); 
    dlg.text = "Dialog"; 
    dlg.orientation = "column"; 
    dlg.alignChildren = ["center","top"]; 
    dlg.spacing = 10; 
    dlg.margins = 16; 

var text = dlg.add("statictext"); 
    text.text = "StaticText"; 

dlg.graphics.backgroundColor = dlg.graphics.newBrush( dlg.graphics.BrushType.SOLID_COLOR, [0.25,0,0.5] );

dlg.show();
```

**And the other one:**

```Javascript
/* 
Code for Import https://scriptui.joonas.me — (Triple click to select): 
{"activeId":2,"items":{"item-0":{"id":0,"type":"Dialog","parentId":false,"style":{"varName":"dlg","text":"Dialog","preferredSize":[0,0],"margins":16,"orientation":"column","spacing":10,"alignChildren":["center","top"]}},"item-1":{"id":1,"type":"StaticText","parentId":0,"style":{"varName":"text","softWrap":false,"text":"Changes errwhere...","justify":"left","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-2":{"id":2,"type":"Button","parentId":0,"style":{"varName":null,"text":"Button","justify":"center","preferredSize":[0,0],"alignment":null,"helpTip":null,"typeName":null}}},"order":[0,1,2]}
*/ 

// DLG
// ===
var dlg = new Window("dialog"); 
    dlg.text = "Dialog"; 
    dlg.orientation = "column"; 
    dlg.alignChildren = ["center","top"]; 
    dlg.spacing = 10; 
    dlg.margins = 16; 

var text = dlg.add("statictext"); 
    text.text = "Changes errwhere..."; 

var button1 = dlg.add("button"); 
    button1.text = "Button"; 
    button1.justify = "center"; 

dlg.show();
```

**Comment by jetrotal** [comment]
it's alright, now i see the problem on these sugestions.

When i wrote them, i had in mind two things:
 - An universal solution to issues like #51
 - And one solution for adding custom tools to their layout, 
like adding a Color Picker next to an specific editText, 
or adding a function from battleStyle ( https://github.com/adamplouff/scriptui-battlestyle ) that "converts" Vector Input into `moveTo()` output inside ScriptUi:
![image](https://cloud.githubusercontent.com/assets/8580225/25320319/f90e1806-2873-11e7-8fc9-3408a0ae6e04.gif)

But i got your point, sorry for spamming these issues.

**Comment by joonaspaakko** [comment]
No problems. Any suggestion is welcome. And I definitely welcome you to argue your point further if you feel the workaround I suggested just doesn't do it for you.

- - - - 

Those creation properties, such as multiline and readonly  ( #51 & #50  ) are troublesome in the sense that you have to define them when the item is created (added). So they can't be placed at the end, like I suggested above. I definitely have `creation properties` in my personal queue _(they may have been for half a year by now... *tugs collar * )_

> I just recently added a new option in the properties panel for buttons called "Button name", which adds the creation property "name" to a button, but you only to buttons and only "ok" or "cancel". I may have to rethink things once I start working on those. It's not like buttons are the only items with the creation property "name"... and it's not like it can only be "ok" or "cancel" either.

**Comment by jetrotal** [comment]
I'm more a designer, than a programmer, that's why i suggested these nasty DIY solutions to whoever needs to fix these creation properties on the go. I really like the flexibillity of them and i got a little frustrated to see they as useless solutions.

That said, i guess the guys from Rainbox have an entire framework with solutions for these kind of issues

![image](https://user-images.githubusercontent.com/45118493/59186152-8c581600-8b48-11e9-9515-ae34bded4e6a.png)
( Print from their wiki: https://rainbox-dev.github.io/DuAEF_Duik/Framework-Reference/DuEditText.html )

They are the biggest reference on scripting for After Effects,
and They released their libraries and framework under GNU License:
https://github.com/Rainbox-dev/DuAEF_Duik

idk... Maybe you can find some insight fiddling with their code

**Comment by joonaspaakko** [comment]
I'm all in with nasty DYI solutions. Too much even... As is evident in how I've ever coded anything. I present evidence n.1 to the court: **SDB**. 

I feel like there may be some sort of misunderstanding somewhere down the line, I am rejecting this issue due to the fact that you can achieve the same thing by defining the changes at bottom of the dialog. But I don't see how this issue has anything to do with creation properties though. At least your examples didn't. I will be adding creation properties, such as the ones you mentioned in #51 and #50, but I'm not seeing the connection between creation properties and the solution you offered in this issue. 

I only skimmed through that SUI library and couldn't find if they are actually allowing you to change creation properties on the fly, but one thing is certain; creation properties can't be changed after the item is created. If they are doing it, they must be using a workaround where they replace the item with a new one with different creation properties. 

Sadly, If you do really want to change creation properties on the fly with SDB, you gotta code that item replacement trick yourself.  I don't think SDB will ever offer custom functions that change creation properties on the fly. That's not a job for SDB, I think.

**Comment by joonaspaakko** [comment]
Again, I'm not exactly sure if we're mixing terminology here or something, but either way, I made you a little example of how you could replace creation properties using SDB.

1. The `editText` item is inside a `group` to make it easier to swap it with another item.
2. When you click the button, this is what happens:
    1. The `editText` item is removed
    2. A new `editText` item is created with the creation property `readonly: true`
        - I am also changing the text to just show that something changed
        - ...and I copy the size form the original item to the new item.

_Check the lines after `// Customization`._

```Javascript
/* 
Code for Import https://scriptui.joonas.me — (Triple click to select): 
{"activeId":1,"items":{"item-0":{"id":0,"type":"Dialog","parentId":false,"style":{"varName":null,"text":"Dialog","preferredSize":[0,0],"margins":16,"orientation":"column","spacing":10,"alignChildren":["center","top"]}},"item-1":{"id":1,"type":"EditText","parentId":5,"style":{"varName":"editText","softWrap":false,"text":"Not readonly","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-2":{"id":2,"type":"Button","parentId":0,"style":{"varName":"makeReadOnly","text":"Make readonly","justify":"center","preferredSize":[0,0],"alignment":null,"helpTip":null,"typeName":null}},"item-3":{"id":3,"type":"StaticText","parentId":0,"style":{"varName":null,"softWrap":false,"text":"...","justify":"left","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-4":{"id":4,"type":"StaticText","parentId":0,"style":{"varName":null,"softWrap":false,"text":"...","justify":"left","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-5":{"id":5,"type":"Group","parentId":0,"style":{"varName":"editTextGroup","preferredSize":[0,0],"margins":0,"orientation":"row","spacing":10,"alignChildren":["left","center"],"alignment":null}}},"order":[0,3,5,1,4,2]}
*/ 

// DIALOG
// ======
var dialog = new Window("dialog"); 
    dialog.text = "Dialog"; 
    dialog.orientation = "column"; 
    dialog.alignChildren = ["center","top"]; 
    dialog.spacing = 10; 
    dialog.margins = 16; 

var statictext1 = dialog.add("statictext"); 
    statictext1.text = "..."; 

// EDITTEXTGROUP
// =============
var editTextGroup = dialog.add("group"); 
    editTextGroup.orientation = "row"; 
    editTextGroup.alignChildren = ["left","center"]; 
    editTextGroup.spacing = 10; 
    editTextGroup.margins = 0; 

var editText = editTextGroup.add("edittext"); 
    editText.text = "Not readonly"; 

// DIALOG
// ======
var statictext2 = dialog.add("statictext"); 
    statictext2.text = "..."; 

var makeReadOnly = dialog.add("button"); 
    makeReadOnly.text = "Make readonly"; 
    makeReadOnly.justify = "center"; 


// Customization
makeReadOnly.onClick = function() {
    toReadonly( editTextGroup );
};

function toReadonly( group ) {
    var originalItem = group.children[0];
    var type= originalItem.type;
    var size = originalItem.size;
    group.remove( group.children[0] );
    var newItem = group.add(type, undefined, undefined, {readonly: true}); 
    newItem.text = "readOnly";
    newItem.size = size;
    group.layout.layout(true);
}

dialog.show();
```

**Comment by joonaspaakko** [comment]
I think we, or at least I concluded that this particular idea is unnecessary, so I'm closing it for now.
