### ISSUE TITLE
Static text is not Aligned in the expired date

### ISSUE THREAD

**Issue by AlexMuc2** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#62]
Hi Joonas,
edittext and statictext could be aligned on your webeditor. But on export, this info is missing on statictext.

static text: 
var statictext12 = group12.add("statictext", undefined, undefined, {name: "statictext12"}); 
edittext
var tx3g1p1 = group3.add('edittext {**justify: "right"**, properties: {name: "tx3g1p1"}}'); 

I'm a complete newbie to ScripUI scripting so the question for me is:
Isn't it possible in ScriptUI or is it a bug in your webeditor? Simply adding it like to the list doesn't work for me like in this sample.
var statictext12 = group12.add("statictext", undefined, undefined, {name: "statictext12", justify: "right"}); 

regards
Michael

**Comment by joonaspaakko** [comment]
I made some changes not too long ago that caused this issue. **Should be fixed now.**

**Comment by AlexMuc2** [comment]
Thanks, that was fast. Seems working now, your editor is great  :-)
And looking at the source it's no wonder that I didm't find it out myself. Now I need to find out how to use it from Plan Applescript... Something with Parameters Passung with doscript and getting the results out from there.

Michael
