### ISSUE TITLE
Single line static text gets extra empty static text field

### ISSUE THREAD

**Issue by trych** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#64]
Whenever I create a single line static text via the SDB, the resulting code seems to

* wrap this line into a group (which I believe is what should happen in a multi line setup instead)
* add an empty static line before the actual static line that I am after

This results in misaligned static text placement in the resulting ScriptUI window (tested in InDesign CS6 and in the latest InDesign CC).

Here is an example.
This is how it looks in the SDB:

![20191023-113717_Screenshot_Firefox](https://user-images.githubusercontent.com/9803905/67379722-8f98ef00-f589-11e9-88ee-39cf98153531.png)

This is the resulting code:

```js
var statictext5 = horGutterGroup.add("group"); 
    statictext5.orientation = "column"; 
    statictext5.alignChildren = ["left","center"]; 
    statictext5.spacing = 0; 

    statictext5.add("statictext", undefined, "", {name: "statictext5"}); 
    statictext5.add("statictext", undefined, "Horizontal:", {name: "statictext5"}); 
    statictext5.helpTip = "Width of the horizontal gutter between single MuGlyphs."; 
```
And this is how it renders in ScriptUI:

![20191023-113859_Screenshot_InDesign](https://user-images.githubusercontent.com/9803905/67379846-c4a54180-f589-11e9-8595-084b189fc525.png)

Once I remove the empty static text field, the alignment pops back into the correct position, but I guess there is still an unneccessary group wrapped around the static text?

**Comment by joonaspaakko** [comment]
Can you post the import code for this section of the dialog? Just as a heads up, it may take several days before I can take a look at this.

**Comment by trych** [comment]
> Can you post the import code for this section of the dialog?

Sure, this should be the relevant section:

```json
"item-69":{
   "id":69,
   "type":"StaticText",
   "parentId":68,
   "style":{
      "enabled":true,
      "varName":null,
      "creationProps":{
         "truncate":"none",
         "multiline":false,
         "scrolling":false
      },
      "softWrap":false,
      "text":"Horizontal:",
      "justify":"left",
      "preferredSize":[
         0,
         0
      ],
      "alignment":null,
      "helpTip":"Width of the horizontal gutter between single MuGlyphs."
   }
}
```
Let me know in case you also need neighboring or parent fields.

**Comment by joonaspaakko** [comment]
I'm still recovering from getting a wisdom tooth pulled on monday, so I may have to come back to this later... but my best guess right now is that you are Firefox and that is the problem. 

**My reasoning:**

- SDB was built to work in Chrome and Chrome only. 
- Your screenshot doesn't have the custom scrollbar that you should have in Chrome. 
- I tried your scenario in Chrome with the import JSON you posted and I got nothing.
- I tried your scenario in Firefox and it treated the single `StaticText` element as a multiline item on export, just like you described.

So if this is the case, I'd suggest you import your dialog to Chrome _or the pseudo desktop app_ and see if the same thing happens.

**Comment by trych** [comment]
> I'm still recovering from getting a wisdom tooth pulled on monday, so I may have to come back to this later...

Oh man, please take it easy then and take your time to recover. The issue is definitively not pressing in any way, so no worries!

Having said that …

> but my best guess right now is that you are using Firefox

Your guess is absolutely correct. I also saw it mentioned that the tool is supposed to work in Chrome only, but since it *looked* like it also works in Firefox, I went ahead and used Firefox anyways. I was expecting that if something would not work in Firefox it would rather be related to the rendering of the (in-browser) dialog or something. I did not expect at all that the generated code itself could be incorrect.

So, in this case this was totally my mistake apparently. 🙈 

If you don't plan to fix this (which is fair enough, as users could easily just use Chrome), might I make the only suggestion that you give a bit of a stronger warning not to use any non-Chrome browser and even better also mention that this might produce incorrect code results? This way users like me won't think the browser suggestion serves only to prevent minor render glitches etc.

Will close this issue now. Thanks for having a look at this. Have a quick recovery!

**Comment by joonaspaakko** [comment]
I have struggled with this before. I just don't know where to draw the line. I've always thought I should prevent full access on other browsers, but at the same time I feel like it's a little too much.

**Comment by trych** [comment]
Don't worry about it, with a specialized tool like this, which is a huge time saver for its users, it is perfectly reasonable to only have it run in a specific browser. I just think there need to be some stronger warnings. Or even completely disable the tool on Firefox and have a clear sign say to use it in Chrome?

**Comment by joonaspaakko** [comment]
As someone who bumped into this issue yourself, what do you think of [this implementation](https://joonas.me/scriptui-chrome-restriction-test)?

- A modal window appears in `!Chrome`.
- Unlike other similar modal windows, this can't be closed by clicking the sides (the overlay).
- This can only be closed by clicking the small link at the bottom.
	- When that link is clicked the message never shows up again... assuming you don't clear browser data or something.

I wasn't too sure if I should show the modal window every single time the page is loaded or not... I decided to let users hide it indefinitely just in case there is some weird detection issue with Chrome or Chromium.

**Comment by trych** [comment]
Generally looks good, I think the problem is more, if you put a sentence like this:

> ScriptUI Dialog Builder (SDB) is designed to work in Chrome and Chromium only.

And then I click `I'm feeling lucky` and see the UI is generally working, I might think: "Hey, it's working anyways. Nice!" And I might build my dialog and not be aware that the resulting output might be buggy. So I would be a bit more explicit about that aspect. Maybe something along these lines:

> ScriptUI Dialog Builder (SDB) is designed to work in Chrome and Chromium only. While the tool might seem to work in other browsers, it will likely produce erroneous output.

Or put this detail in the small text below, but I think the important part is that the resulting code can be erroneous, which is what I did not expect once i saw the UI generally working.

**Comment by joonaspaakko** [comment]
You're right, @trych. In fact, I decided to take it a step further and remove the `I'm feeling lucky` button. Its only purpose was to be a crutch in case of false positives, which I think won't be a problem... I was just trying to be extra careful.

So now the message shows up every single time and the is no way to get rid of it other than switching the browser: [**link**](https://joonas.me/scriptui-chrome-restriction-test) (same link as before).

There may be users who have been using SDB on other browsers and when I put this message in place they will get locked out. I considered adding a message saying like "post an issue in github if you need access to a dialog you made in this browser", but I felt the message was already kinda long and I'm sure people who reaaaally feel like they need it, they will either figure out they can inspect the overlay into oblivion or come and ask for help.

I'm still not a 100% satisfied with the message. Like I said, I feel it's unnecessarily long. I'm just not much of a wordsmith, but I think it'll do. It should be better than the small warning I have in place right now.

**Comment by trych** [comment]
Yes, I think now it's actually better.

And about the locked out issue: Usually – with normal websites – that would and should be a real concern. However, in this case you are providing a very specialized (and highly sophisticated!) tool for a very specific job. So, if somebody want so to take advantage of this tool, then it is not to much to ask this person to use a certain browser for this task.

So I think blocking the tool on non-Chrome browsers entirely is actually the best way, since it prevents bugs that are (for the users) hard to track down or to even notice in some cases.
