### ISSUE TITLE
 The multiselect property in listbox cannot be unchecked

### ISSUE THREAD

**Issue by lcolok** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#65]
ScriptUI-Dialog-Builder is a great job! It led me to get started and mastered the ae script UI code. Now I even rely too much on it. But I found when I select two or more items of listbox in the preview area, it will automatically export the property of multiselect as "True". This setting led to a bug in my script,that it just accept the only choice. I took about a hour to review all parts of my script and fix it. I suggest that any operation in preview area will not change the params of whole construction process.

**Comment by joonaspaakko** [comment]
Let me know if I got this right: You wouldn't have had this issue, had you not selected multiple items by coincidence?

I think I'd lean heavily on that being a user error. Every item in the dialog preview works with the logic of what you see if what you get (*more or less*): Expanded Treeview item exports expanded. Checked radio button exports checked. Even selected tabs export that way.

Wouldn't it be more confusing if you select multiple items in a listbox and it exports with just one selected? Simply making it so doesn't really sound good to me, but maybe there's something else that could be done to avoid issues... A warning perhaps?

**Comment by lcolok** [comment]
Thank you for your attention to this issue.

You're right. I selected multiple items by coincidence.

 A warning toast or dialog may be annoying. It is better to have the _multiselect_ property checkbox and the _listbox_ in the preview area be two-way binding. The checkbox will turn on while selected multiple items. Conversely the multiple items will be cancel while the checkbox is turn off.

**Comment by joonaspaakko** [comment]
If I were to entertain making this better, it would have to be done like this:

1. **Selecting 2 items checks the checkbox**
2. **Unchecking the checkbox removes the selection**
3. **Checking the checkbox doesn't do anything to the selected items**
    - If this did happen, you wouldn't be able to add the `multiselect` property without items getting selected. Many reasons why you'd want to allow users to make multiple selections but start without any.
4. **Deselecting items doesn't do anything to the checkbox**
    - Same reason as before...

I kinda feel like this is a negligible thing and probably would be fine if I kept it the way is.

> The `EditText` item has a similar disconnect, where no matter what the `multiline` property is, the property is force fed to the item on export, if the it's in multiple lines in the preview.

**Comment by lcolok** [comment]
> If I were to consider making this better, it would have to be done like this:
> 
> 1. **Selecting 2 items checks the checkbox**
> 2. **Unchecking the checkbox reduces the selection to 1 item**
> 3. **Checking the checkbox doesn't select any items**
>    
>    * If this did happen, you wouldn't be able to add the `multiselect` property without items getting selected. Many reasons why you'd want to allow users to make multiple selections but start without any.
> 4. **Deselecting items doesn't do anything to the checkbox**
>    
>    * Same reason as before...
> 
> Because I can't sync them all the way, I kinda feel like this is a negligible thing and probably would be fine if I kept it the way it is.
> 
> > The `EditText` item has a similar disconnect, where no matter what the `multiline` property is, the property is force fed to the item on export, if it's in multiple lines in the preview.

That's true. It's a negligible issue. Or this is a once-in-a-lifetime case of an ae script/extensions/plugins developer. Thank you for your patience.
