### ISSUE TITLE
Suggestion: Show Group's "Custom Name" on the Structure Panel

### ISSUE THREAD

**Issue by jetrotal** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#66]
We are able to easily find any Item on the Structure Panel by looking to the item's name.
That doesn't apply to Group Items (and Tabbed Panels too i guess):
![image](https://user-images.githubusercontent.com/45118493/69595503-7d71fc80-0fde-11ea-95e7-1cb4d15a4058.png)

The Structure panel looks for the "Text" input from the Item Properties Tab in order to Tag a name on an Item.

Maybe, the panel could look for the "Custom Name" when an Item doesn't have the "Text" property.

Thanks once again for this amazing tool :}

**Comment by joonaspaakko** [comment]
You suggested the custom name would be used if the text property doesn't exist, or I guess if it is empty as well.

This thought has crossed my mind before but my thought was that If they both exist, the custom name is used instead. 

I'm just not sure if that makes more sense, but that way you would always be able to see the custom name out in the open and I think it would help users figure out which items have a custom names, without clicking through every single one. Maybe they could even have a slightly different color too so you can easily identify it for what it is.

**Comment by jetrotal** [comment]
hm... the idea is interesting...
But i think this many color variations could confuse a first-time user...

Maybe you could mimic Blender "Collections" Panel:
![image](https://user-images.githubusercontent.com/45118493/69643916-b5129000-1042-11ea-80b2-94ff563c6729.png)

They preffer to use icons to show the user the type of an item,
and always use the variable name instead of the item name to tag it.

**Comment by joonaspaakko** [comment]
I wanted to say that this might have to wait until January 2020. I'm going to try to do this and some other changes before that, but it's not looking like that's possible.

**This a reminder for me:**

1. For now, I think the plan is this → Custom name replaces the type name and when that happens type becomes a `title="group"`.
	- This way you could still see the type by hovering over the item. Not ideal but better than nothing.
	- I like the idea of having color coding, but I also kinda feel like it breaks the layout a little bit. Maybe it's not too bad though... It would help the user see all the custom named items at glance... That I definitely like.
	- I was thinking... if the color coding seems too much, maybe I could add a toggle so that users can disable it, much like the dialog preview light icon. Although this would have to be persistent.
2. I should see if I can make the type icons work, but I have a feeling it won't look so great with the `remove` → `X`'s. Or maybe the icon could be visible for the active item only. Maybe I should forget about that and just include the type in the properties panel.

**Comment by jetrotal** [comment]
I tested resizing the icons size by 10% and replacing the **X** icons

here's a mockup:
![image](https://user-images.githubusercontent.com/45118493/70172205-f5ab8280-16ae-11ea-96a9-ef09c02019b8.png)

Is the overall look too messy like this?

**Comment by joonaspaakko** [comment]
Compared to the uniform X's, it is messier, but In general not as much as I thought.
What about removing the items? By clicking the icons? Context menu? Mouse over the item turns it into an x?

While this seems quite plausible, it bothers me a little that removing items would become less obvious and it does look a bit chaotic I  comparison to the X's. I'm thinking moving the type to the properties panel might be the lesser evil in this case. I think I may have to try this icon thing to decide.

**Comment by jetrotal** [comment]
hm...
What about moving the X to the Item Properties tab?

![image](https://user-images.githubusercontent.com/45118493/70180961-c4877e00-16bf-11ea-855f-866ca115b3eb.png)


You could also include some buttons that are hard to find, like the Hide/Show Item or the Copy/Duplicate item.

I suggest changing the "Custom Name" to "Item Name", so you can always show the default Name Value, when creating a new item, for example: 
` {name: "group1"}); `

**Comment by joonaspaakko** [comment]
@jetrotal, I'm testing the custom name thing. The way it works right now comes from how I originally built the naming system. The item numbering always goes top-down `1,2,3,4`. Move `group1` below `group2` and their names get switched. Of course, if you give unique custom names, this won't happen.

> It is a little odd behavior, but I'd say acceptable. Rewriting how item names work would be a lot of work...

https://scriptui.joonas.me/test/?load=sample

Icon tests:

I still can't get fully behind the idea of adding type icons to the structure panel. First of all, I don't think custom names replacing types necessitate icons, so there's that. I also feel that whatever they bring to the table is kinda negated by the visual clutter they add, not to mention the further compromises they add, like removing or relocating the `remove item` icons. I'm not planning to add these icons, but I wanted to show you anyways.

1. [Icons](https://scriptui.joonas.me/test/?load=sample&icons=true)
2. [Icons → No item removal X](https://scriptui.joonas.me/test/?load=sample&icons=true&remove=false)
3. [Gray icons](https://scriptui.joonas.me/test/?load=sample&icons=true&iconColor=gray)
4. [Gray icons → No item removal X](https://scriptui.joonas.me/test/?load=sample&icons=true&iconColor=gray&remove=false)

**Comment by jetrotal** [comment]
hm... the naming system is clever, and works well.
Adding the default name to the "Custom Name" text input could help new users locating where they can change the name...

The icons indeed looks messy, maybe they look too much like the "Add items" menu, or maybe the spacing is too short...
![image](https://user-images.githubusercontent.com/45118493/85937241-1e5bc980-b8d8-11ea-9581-bb8298f24133.png)
Here i tested adding a left-padding to the icon and increasing the line-height of each item.

here's the same test, using the color from the line below
![image](https://user-images.githubusercontent.com/45118493/85937261-3df2f200-b8d8-11ea-8d4c-934b5163199a.png)


Just testing things around, maybe it's better with no icons at all.

**Comment by joonaspaakko** [comment]
So yea, I decided to leave out the icons for now. If it didn't cause as much head-scratching and compromises I would've added it, but as it stands I don't think it really brings enough to the table.
