### ISSUE TITLE
dns issues?

### ISSUE THREAD

**Issue by mcsinc** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#74]
Looks like you site is having trouble resolving dns.

**Comment by joonaspaakko** [comment]
I'm halfway writing an email to my service provider. I'll get it resolved :)

**Comment by joonaspaakko** [comment]
That was interesting. They had changed name servers, written a post on the website and I guess that was good enough for them.

Now I've updated them and the site should be up soon...ish. You know, few days at most.

I'll close this once domain name is back up...

**Comment by mcsinc** [comment]
Its why I set my time to refresh to 1 hr. I believe you can still adjust the to force refresh after change. At least with Godaddy you can. I feel the pain it has happened to me before.

**Comment by joonaspaakko** [comment]
I'm not super knowledgeable about this stuff, but I don't see how it could've been avoided? My host changed their name server addresses, which I had to manually change at my domain name service provider. 

**Site is back up now.**
