### ISSUE TITLE
Suggestion: Item array separated from items

### ISSUE THREAD

**Issue by ggs67** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#80]
Maybe I am missing something, but I am currently developping a wrapper class for dialogs built with SDB. In this class I use the function wrapper and the variable name reference list feature of SDB.

I do not understand why SDB pout the array of items insaide of items (e.g. dialog.items.array), risking a name collision with an item called array, and not directly in th edialog as dialog.array ?

**Comment by joonaspaakko** [comment]
I'm going to have to take a better look later but my guess is that it's a mistake.

**Comment by joonaspaakko** [comment]
I fixed it by changing it into `dialog.itemsArray`.

By the way, I don't know what you're using the reference list for, so just putting it out there that it is definitely super redundant as anything but a human readable reference list. I mean, I made it an object and everything, just to perhaps make it more useful, but there are already 3 different ways to access items within the dialog. So given that it is no on by default, the more reliable way to access items within the dialog in any situation would be `dialog.findElement("itemName")`.

**Comment by ggs67** [comment]
Great! That this was a mistake was my first thought as well,. But then I feared I would be missing something here. 

You are right, I do use these structures for convinience. I use the array to seek for some fields, avoiding me to have to go through the window tree. And the reference list for fast location of the fields by name. I do wrap all up into a TDialog, TDialogField and TxxxValidator classes. 

This said, I am thinking it may be a good idea to put the fields into the reference class immediatally, i.e. non-redundant and by default. This especially in a UI builder where the user is often not thinking about name colisions with windows properties/methods. This can be fully  avoided by puitting all dialog elements in their own name space (e.g. the items dictionary.
