### ISSUE TITLE
Horizontal tab menu keeps crashing

### ISSUE THREAD

**Issue by schroef** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#81]
Im not sure what issue i have with my setup. I tried both 2017 cc and 2018 cc, 2 old versions i only have. The dialog shows  all seems to function, but when i cancel or press excecution button Illustrator crashes. It happens in both my illustrators versions i have. Im on OSX and tried it as well on different OS versions.

First i thought perhaps to common names for the variables, so i gave all a custom name. Still crashes. There must be something in there causing an issue.

Ive attached the stripped JSON part
[Specify-Horizontal Tabs-05.json.zip](https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/files/4631695/Specify-Horizontal.Tabs-05.json.zip)

**Comment by schroef** [comment]
Even this super simple version, it only contains 2 tabs, crashes when pressing escape

[horizontal-tab-dialog.jsx.zip](https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/files/4631768/horizontal-tab-dialog.jsx.zip)

**Comment by schroef** [comment]
I did just find this, but i cant test it. I cant upgrade due to my old OS on my old MacBook :(

https://helpx.adobe.com/indesign/kb/troubleshoot-issues-indesign-cc-2017_1.html

**Comment by joonaspaakko** [comment]
Yes. I'm aware of this issue existing in both AI and ID... I can also confirm it has been fixed in both via normal updates by now. This never had a hotfix for AI, as far as I know. 

I guess the only way to get around is to drop the tabbedPanel layout or update the application. There could be a JS workaround, but I don't know if anyone ever came up with one. I can't help with trying to come up with one either, because all my apps are way past the problematic versions. As I remember it, you could make the most barebones tabbedPanel and it would still crash, so not sure if anything can be done about it aside from just try/catch excluding the tabbedPanel, but that really isn't an option. 

- - - - -

Posted a new issue because I noticed some hidden items in your SDB dialog were only partially commented out causing just a general invalid JS error. That one I can fix.

**Comment by joonaspaakko** [comment]
I wonder if something like this would help (custom code at the bottom)? Not sure if `sleep` and `update` are necessary. I mean I don't know if this fixes the issue, but you could give it a shot.

Note that a click event on the button named `cancel` replaces the `Esc` key behavior too.

```js
/*
Code for Import https://scriptui.joonas.me — (Triple click to select):
{"activeId":0,"items":{"item-0":{"id":0,"type":"Dialog","parentId":false,"style":{"enabled":true,"varName":null,"windowType":"Dialog","creationProps":{"su1PanelCoordinates":false,"maximizeButton":false,"minimizeButton":false,"independent":false,"closeButton":true,"borderless":false,"resizeable":false},"text":"Dialog","preferredSize":[0,0],"margins":13,"orientation":"row","spacing":34,"alignChildren":["center","top"]}},"item-1":{"id":1,"type":"TabbedPanel","parentId":0,"style":{"enabled":true,"varName":null,"preferredSize":[0,0],"margins":10,"alignment":null,"selection":2}},"item-2":{"id":2,"type":"Tab","parentId":1,"style":{"enabled":true,"varName":null,"text":"Tab","orientation":"column","spacing":10,"alignChildren":["left","top"]}},"item-3":{"id":3,"type":"Tab","parentId":1,"style":{"enabled":true,"varName":null,"text":"Tab","orientation":"column","spacing":10,"alignChildren":["left","top"]}},"item-4":{"id":4,"type":"Button","parentId":6,"style":{"enabled":true,"varName":"cancel","text":"Cancel","justify":"center","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-5":{"id":5,"type":"Button","parentId":6,"style":{"enabled":true,"varName":"ok","text":"OK","justify":"center","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-6":{"id":6,"type":"Group","parentId":0,"style":{"enabled":true,"varName":null,"preferredSize":[0,0],"margins":0,"orientation":"column","spacing":10,"alignChildren":["fill","center"],"alignment":null}}},"order":[0,1,2,3,6,4,5],"settings":{"importJSON":true,"indentSize":false,"cepExport":false,"includeCSSJS":true,"showDialog":false,"functionWrapper":false,"afterEffectsDockable":false,"itemReferenceList":"None"}}
*/

// DIALOG
// ======
var dialog = new Window("dialog");
    dialog.text = "Dialog";
    dialog.orientation = "row";
    dialog.alignChildren = ["center","top"];
    dialog.spacing = 34;
    dialog.margins = 13;

// TPANEL1
// =======
var tpanel1 = dialog.add("tabbedpanel", undefined, undefined, {name: "tpanel1"});
    tpanel1.alignChildren = "fill";
    tpanel1.preferredSize.width = 119.531;
    tpanel1.margins = 0;

// TAB1
// ====
var tab1 = tpanel1.add("tab", undefined, undefined, {name: "tab1"});
    tab1.text = "Tab";
    tab1.orientation = "column";
    tab1.alignChildren = ["left","top"];
    tab1.spacing = 10;
    tab1.margins = 10;

// TAB2
// ====
var tab2 = tpanel1.add("tab", undefined, undefined, {name: "tab2"});
    tab2.text = "Tab";
    tab2.orientation = "column";
    tab2.alignChildren = ["left","top"];
    tab2.spacing = 10;
    tab2.margins = 10;

// TPANEL1
// =======
tpanel1.selection = tab1;

// GROUP1
// ======
var group1 = dialog.add("group", undefined, {name: "group1"});
    group1.orientation = "column";
    group1.alignChildren = ["fill","center"];
    group1.spacing = 10;
    group1.margins = 0;

var cancel = group1.add("button", undefined, undefined, {name: "cancel"});
    cancel.text = "Cancel";

var ok = group1.add("button", undefined, undefined, {name: "ok"});
    ok.text = "OK";



// Custom stuff...
cancel.onClick = function() {
  dialog.remove( tpanel1 );
  $.sleep(100);
  dialog.update();
  dialog.close();
}

dialog.show();
```
