### ISSUE TITLE
listbox Creation Properties wrongly quoted

### ISSUE THREAD

**Issue by GuidoEijrond** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#87]
When adding a listbox some properties are wrongly quoted,
like `columnTitles` and `numberOfColumns`.
This results in a broken listbox to which we cannot add subItems.

Problem:
`var info_listbox = info_grp.add("listbox", undefined, undefined, {name: "info_listbox", numberOfColumns: "3", columnTitles: "["A", "B", "C"]", showHeaders: true});`

Expected:
`var info_listbox = info_grp.add("listbox", undefined, undefined, {name: "info_listbox", numberOfColumns: 3, columnTitles: ["A", "B", "C"], showHeaders: true});`

Workaround:
manually edit the exported code
or add the listbox separately.

**Comment by joonaspaakko** [comment]
Thanks for the post @GuidoEijrond. Should be fixed now.
