### ISSUE TITLE
CPU firing up after export (or window open in background)

### ISSUE THREAD

**Issue by worldoptimizer** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#88]
The tool is such a time save. First off … thank you. I just started out with building dialogs and will progress to HTML in the near future. One thing I noticed is that the CPU on my laptops starts going wild and the fans fire up when I leave the script UI builder open (your hosted version).

**Comment by joonaspaakko** [comment]
Closed for inactivity...
