### ISSUE TITLE
button on extra pop up dialog not working

### ISSUE THREAD

**Issue by SebastianMorenoAgredo** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#89]
Thanks for your great work first of all, more than an Issue I have a question. 
I am triggering a second panel (Modeless) with: csi.requestOpenExtension('newHtmlPanel') and this window has a button that I can't make it work  with:   $(button1).find('> div').on("click", function () {   functionWhenClicking();   }); 
do you know what could it be?

**Comment by joonaspaakko** [comment]
I'm not incredibly familiar with CEP, I'm not sure if I can help with that, but I think the way you would have to do it is by passing over data with event(s). I'm pretty sure that you can't just open the second extensions and directly control it as if it was part of the first extension, which I think is kinda what your example code assumes... This second extension would have to have its own logic. 

It would go something like this: you make the first extension listen for a specific (custom) event, then you programmatically open the second extension, which later on dispatches the (custom) event whenever it's ready to do so and in this custom event you smuggle over whatever data you need. The event listener in the first extension is what receives that data. But all of the interactivity happening in the second extension you would write for that extension specifically (much like what you've already done with the first extension), like this click event you have, you'd put that in the second extension.

I think the CEP cookbook doc has an example on listening for events and dispatching events in this way.

It could also be that what I'm saying is completely false or maybe there's a better way to do it. I've never actually done it myself and I've barely made any CEP extensions in general.

**Comment by SebastianMorenoAgredo** [comment]
Thanks man for your answer, I think you are right I keep bumping into the EventListener and the dispatching 
https://community.adobe.com/t5/exchange/html5-opening-a-modal-dialog-from-extension/td-p/6070660?page=1 
It is also my first time with a CEP and it is so hard to do something so simple like a pop up in Premiere with an input field..
I think you are right but I honestly don't know the syntax so well, I do all by trial and error. Let's see I will keep digging and  I appreciate the help

**Comment by joonaspaakko** [comment]
@SebastianMorenoAgredo, if it doesn't go against your original idea/use-case, you could potentially do something similar to what was suggested as the first workaround and open SDB's dialog inside the _first_ extension as a sort of a modal popup: https://codepen.io/joonaspaakko/pen/vYKOWLy

**Comment by SebastianMorenoAgredo** [comment]
Genius!!! it could work.. I will try it out and let you know.

**Comment by joonaspaakko** [comment]
I closed this this for now but you can still comment on it if needed. It just takes it off the front page of issues.
